---
- name: Using vos_action module
  hosts: vision_npb

  tasks:
  - name: Configuration backup
    vos_actions:
      action: export
      settings:
        boundary: INCLUDE
        export_type: FULL_BACKUP
        file_name: /home/testuser/configuration_backup/files/
